name: "Feature Request"
description: Request a new feature in JellyCommands
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the feature
      description: A detailed description of the feature would be awesome, but not required.
      placeholder: I want x because...
    validations:
      required: false
